# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74fc5e7d43e8f9bb7e4966eaceb4d9aa8e94356f7f5ffd31c5af1dc79549f04217650744ab7a4377461c5ac1679714a4abdb83a90ca3548292ac9ebcd256e8c
  domain_name: <%= ENV["SITE_URL"] %>

test:
  secret_key_base: b4598c56d176d92c6e0567190b9af5d5d780e201a14d4da616ba143b2ca5992243eb26f4fa1a12873902138676b4a31d2d2f5269cae1d924170006b4a9db7b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["SITE_URL"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_authentication_type: <%= ENV["SMTP_AUTHENTICATION_TYPE"] %>
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>